[env:esp32c3_base]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

build_unflags = -std=gnu++11
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -std=c++17

monitor_speed = 115200

[env:board1]
extends = env:esp32c3_base
;upload_port = /dev/ttyESP-50:78:7D:91:F2:1C
;monitor_port = /dev/ttyESP-50:78:7D:91:F2:1C

upload_port=/dev/ttyESP-50:78:7D:8F:D7:E4
monitor_port=/dev/ttyESP-50:78:7D:8F:D7:E4

[env:board2]
extends = env:esp32c3_base
;upload_port = /dev/ttyESP-50:78:7D:8F:D7:D0
;monitor_port = /dev/ttyESP-50:78:7D:8F:D7:D0

upload_port = /dev/ttyESP-58:8C:81:AD:2B:B0
monitor_port = /dev/ttyESP-58:8C:81:AD:2B:B0
